# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-23 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeformapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodels',
            name='ebalaji',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='employeemodels',
            name='esal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
