# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeformapp', '0002_auto_20190923_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodels',
            name='emastan',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
