# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeformapp', '0003_employeemodels_emastan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodels',
            name='emastan',
        ),
        migrations.AddField(
            model_name='employeemodels',
            name='erahul',
            field=models.IntegerField(default='9'),
        ),
    ]
