# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeformapp', '0004_auto_20190924_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodels',
            name='erahul',
        ),
    ]
