# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeformapp', '0005_remove_employeemodels_erahul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodels',
            name='esal',
            field=models.IntegerField(default=True),
        ),
    ]
