# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeformapp', '0006_auto_20190924_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodels',
            old_name='ebalaji',
            new_name='ebalaj',
        ),
    ]
