# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeformapp', '0007_auto_20190924_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodels',
            name='emastan',
            field=models.IntegerField(default=None),
        ),
    ]
