# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeformapp', '0008_employeemodels_emastan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodels',
            name='etak',
            field=models.IntegerField(default=89),
            preserve_default=False,
        ),
    ]
